default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *default
  database: vcbc_dev

test:
  <<: *default
  database: vcbc_test

production:
  url: <%= ENV['DATABASE_URL'] %>
